require('illuminate').configure({
  filetypes_denylist = {
    '',
    'TelescopePrompt',
    "NvimTree",
    "packer",
    "netrw",
    "dapui_scopes",
    "dapui_breakpoints",
    "dapui_stacks",
    "dapui_watches",
    "dap-repl",
    "toggleterm",
    "input",
    "output",
    "lspinfo",
    "toggleterm"
  },
})
