-- require 'colorizer'.setup {
--   html = {
--     RGB      = true;         -- #RGB hex codes
--     RRGGBB   = true;         -- #RRGGBB hex codes
--     names    = true;         -- "Name" codes like Blue
--     RRGGBBAA = true;        -- #RRGGBBAA hex codes
--     rgb_fn   = true;        -- CSS rgb() and rgba() functions
--     hsl_fn   = true;        -- CSS hsl() and hsla() functions
--     css      = true;        -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
--     css_fn   = true;        -- Enable all CSS *functions*: rgb_fn, hsl_fn
--     -- Available modes: foreground, background
--     mode     = 'background'; -- Set the display mode.
--   };
--   css = {
--     RGB      = true;         -- #RGB hex codes
--     RRGGBB   = true;         -- #RRGGBB hex codes
--     names    = true;         -- "Name" codes like Blue
--     RRGGBBAA = true;        -- #RRGGBBAA hex codes
--     rgb_fn   = true;        -- CSS rgb() and rgba() functions
--     hsl_fn   = true;        -- CSS hsl() and hsla() functions
--     css      = true;        -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
--     css_fn   = true;        -- Enable all CSS *functions*: rgb_fn, hsl_fn
--     -- Available modes: foreground, background
--     mode     = 'background'; -- Set the display mode.
--   };
--   javascript = {
--     RGB      = true;         -- #RGB hex codes
--     RRGGBB   = true;         -- #RRGGBB hex codes
--     names    = true;         -- "Name" codes like Blue
--     RRGGBBAA = true;        -- #RRGGBBAA hex codes
--     rgb_fn   = true;        -- CSS rgb() and rgba() functions
--     hsl_fn   = true;        -- CSS hsl() and hsla() functions
--     css      = true;        -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
--     css_fn   = true;        -- Enable all CSS *functions*: rgb_fn, hsl_fn
--     -- Available modes: foreground, background
--     mode     = 'background'; -- Set the display mode.
--   };
-- }

vim.g.Hexokinase_ftEnabled = {'css', 'html', 'javascript'}
vim.g.Hexokinase_highlighters = { 'virtual' }
-- vim.g.Hexokinase_highlighters = { 'virtual', 'sign_column', 'background',
-- 'backgroundfull', 'foreground', 'foregroundfull' }
